### ISSUE TITLE
use sails-mysql-transactions rollback fail,  but mysql terminal success

### ISSUE THREAD

**Issue by Mararesliu** [postmanlabs/sails-mysql-transactions#17]
use sails-mysql-transactions rollback fail, mysql log is right, but can not rollback.

**Comment by shamasis** [comment]
Hope you're using the latest version. 

Can you post a snippet if code that you're using and also what's the exact error message?

**Comment by Mararesliu** [comment]
Thx, i use newest version 0.3.2. 
In controller snippet code
 // start a new transaction
        Transaction.start(function (err, transaction) {
            if (err) {
                // the first error might even fail to return a transaction object, so double-check.
                transaction && transaction.rollback();
            }
            var attributes = {
                order_sn : order.order_sn
                 .....
            };
           OrdersModel.transact(transaction).create(
                attributes, 
                function (err, orderModelInstance) {
                    if (err) {
                        transaction.rollback();
                        return;
                    }
                 //test rollback
                  transaction.rollback();
             });
     });
in mysql query log, it seem work, but insert successful, not rollback
   63 Query	START TRANSACTION
   61 Query	INSERT INTO `orders` (`order_sn`,....) values ('xxxxxx',....')
   63 Query	ROLLBACK

**Comment by shamasis** [comment]
Let me reproduce this locally.

**Comment by shamasis** [comment]
I replicated your exact code, just to be sure... but no luck reproducing the issue :-(

Can you double check whether you are using the correct `connection` for the `OrdersModel` in your config?

In my test code I did the following in `local.js`
```
  connections: {
    mySQLT: {
      adapter: 'sails-mysql-transactions',
      host: '127.0.0.1',
      user: 'root',
      password: '',
      database: 'test'
    }
  },

  models: {
    connection: 'mySQLT',
    migrate: 'alter'
  }
```

I have also attached the zipped archive of my testing code. https://www.dropbox.com/s/iz9wg1h9eam26xw/smt-issue-gh17.zip?dl=0 (PS: You might want to change the config/local.js to point to a valid local db username and password.)

Am closing the issue for now. If you still have issues, feel free to reopen. :-)
