### ISSUE TITLE
sails-mysql-transactions issues while integerating

### ISSUE THREAD

**Issue by sapnajindal** [postmanlabs/sails-mysql-transactions#34]
I am trying to install sails-mysql-transactions. I have uninstalled sails-mysql added sails-mysql-transactions to postscript, already having sails 0.11.4 installed, then also i am not able to install the adapter. Gives an error when i do npm install ,
test-app@0.0.1~postinstall: cannot run in wd %s %s (wd=%s) test-app@0.0.1 npm install sails-mysql-transactions /home/vagrant/www/test-app
- serve-static node_modules/sails/node_modules/serve-static

**Comment by shamasis** [comment]
Can you post here what does the post install script file look like? Or is it directly in package.json. If yes, then what is the value of post install script in package.json?

**Comment by sapnajindal** [comment]
@shamasis  Posting my question from previous thread here.

**Comment by sapnajindal** [comment]
@shamasis I checked the Readme, which is saying we get an additional field when we do update for a model and it contains all the previous values. I am facing two problems here: 
-- Model.update({id:1},{name:'test'}).exec(function(err,updated,prev){})

If i run the above i get an array of json in updated
updated : [ { id:1,name:'test' } ] prev : [{}]

but if i run Model.update({id:1},{name:'test'}).then(function(updated,prev){}).catch(function(err){})

updated :[ [ { id:1,name:'test' } ], [{}] ] prev : undefined

Why is this behavioural change if i use then instead of exec ? Its creating lot of complications for me.

-- **and why is the prev always empty?**

**Comment by sapnajindal** [comment]
@shamasis I tried passing transaction object in values to the model like below

Transaction.start(function(err,transaction){
Model1.transact(transaction).create({name:'fd'},function(err, model1){
Model.transact(transaction).create({model1Id:, model1.id, transaction : transaction})
})
})
In Model.js

beforeCreate(values,callback){
Model1.transact(values.transaction).findOne({id: values.model1Id})
}
But by doing this i am getting an error in beforecreate

self._transaction.id is not a function
at [object Object].util.extend.findOne (/home/vagrant/www/testProject/node_modules/sails-mysql-transactions/lib/mediator.js:139:36)
at /home/vagrant/www/testProjecti/api/models/v1/Model.js:112:59
at bound (/home/vagrant/www/consumer-payments-api/node_modules/sails/node_modules/waterline/node_modules/lodash/dist/lodash.js:957:21)

**Comment by sapnajindal** [comment]
@shamasis  In the readme, its mentioned that whenever we update sails we need to reinstall this adapter as well. I didnt get this thing. 
If i do sails update, by post install script , should i update the sails-mysql-transaction version as well?
Its not very much clear.

**Comment by shamasis** [comment]
@shamasis In the readme, its mentioned that whenever we update sails we need to reinstall this adapter as well.

-- this adapter injects its own version of Warerline into sails. So, if you reinstall sails, that injection will be gone. So, you'll need to simply run NPM install sails-mysql-transactions again.

**Comment by shamasis** [comment]
> Why is this behavioural change if i use then instead of exec ? Its creating lot of complications for me.

.then does not support the previous value yet as it was not there in original waterline. Feel free to submit a PR for this as it will take a while for me to get around to supporting this.

**Comment by shamasis** [comment]
> self._transaction.id is not a function

That's not a right way of using transact function. The transact function expects the transaction object returned when you did Transaction.start

So, find a way to forward this object to the model service.

**Comment by sapnajindal** [comment]
@shamasis I am getting following error -

```
AdapterError: Invalid connection name specified
    at getConnectionObject (/home/vagrant/www/consumer-payments-api/node_modules/sails-mysql-transactions/sails-mysql/lib/adapter.js:1184:35)
    at spawnConnection (/home/vagrant/www/consumer-payments-api/node_modules/sails-mysql-transactions/sails-mysql/lib/adapter.js:1099:7)
    at Object.module.exports.adapter.join (/home/vagrant/www/consumer-payments-api/node_modules/sails-mysql-transactions/sails-mysql/lib/adapter.js:510:16)
    at Object.adapter.(anonymous function) [as join] (/home/vagrant/www/consumer-payments-api/node_modules/sails-mysql-transactions/lib/adapter.js:114:23)
    at [object Object].module.exports.join (/home/vagrant/www/consumer-payments-api/node_modules/sails/node_modules/waterline/lib/waterline/adapter/dql.js:53:13)
    at [object Object]._runOperation (/home/vagrant/www/consumer-payments-api/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:400:29)
    at [object Object].run (/home/vagrant/www/consumer-payments-api/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:69:8)
    at [object Object].module.exports.findOne (/home/vagrant/www/consumer-payments-api/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:69:16)
    at [object Object].wrapper (/home/vagrant/www/consumer-payments-api/node_modules/lodash/index.js:3095:19)
    at [object Object].Deferred.exec (/home/vagrant/www/consumer-payments-api/node_modules/sails/node_modules/waterline/lib/waterline/query/deferred.js:561:16)

```

I am not able to figure out why? And also this error goes when i reload the application

**Comment by sapnajindal** [comment]
@shamasis We are using sails-db-migrate in my application for sails, i get this error ;

```
Running "db:migrate:create" (db:migrate) task
+ db-migrate create add-transactionId-tables
Fatal error: migrations not supported for sails-mysql-transactions
```

This is a severe problem, Please suggest a way by which i can use migrations with this adapter.

**Comment by sapnajindal** [comment]
@shamasis Regarding 
`AdapterError: Invalid connection name specified`

Please Provide a reason for the above error, i am getting this error quite a lot of times now. Not able to figure out the reason.

**Comment by sapnajindal** [comment]
@shamasis 

I am having a find Query to fetch all the values, like -
`Model.find().populate('model1').populate('model2')`

With sails-mysql adapter it was working very much fine, but with using sails-mysql-transactions, its taking way too much time to fetch the data, in the end gives the error below:

```
app-0 FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
app-0 <--- Last few GCs --->
app-0   103881 ms: Mark-sweep 1389.0 (1457.0) -> 1393.7 (1457.0) MB, 1090.2 / 0 ms [allocation failure] [GC in old space requested].
app-0   104971 ms: Mark-sweep 1393.7 (1457.0) -> 1393.7 (1457.0) MB, 1090.0 / 0 ms [allocation failure] [GC in old space requested].
app-0   106073 ms: Mark-sweep 1393.7 (1457.0) -> 1388.3 (1457.0) MB, 1102.0 / 0 ms [last resort gc].
app-0   107180 ms: Mark-sweep 1388.3 (1457.0) -> 1388.5 (1457.0) MB, 1107.2 / 0 ms [last resort gc].
app-0 <--- JS stacktrace --->
app-0 ==== JS stack trace =========================================
app-0 Security context: 0x3b9def337399 <JS Object>
app-0     1: _getValue [/home/ubuntu/www/consumer-payments-api/node_modules/sails/node_modules/waterline/lib/waterline/model/lib/association.js:~34] [pc=0x210827aeb20d] (this=0x2e64e10296b1 <JS Object>)
```

**Comment by shamasis** [comment]
> With sails-mysql adapter it was working very much fine, but with using sails-mysql-transactions, its taking way too much time to fetch the data.

Unlikely, since sails-mysql-transactions uses sails-mysql inside.

**Comment by sapnajindal** [comment]
@shamasis I am using sails db migrate for migrations which sails-mysql-transactions dont support. Thats why i am using a different connection for migrations using sails-mysql. I have not installed sails-mysql , its using the one present in your module.
My local.js looks something like below -

```
connections: {
    mysqlDbDev: {
      adapter : 'sails-mysql-transactions',
      host    : 'localhost',
      port    : 3306,
      user    : 'root',
      password: '',
      database: 'consumer_payment',
      rollbackTransactionOnError: true,
      queryCaseSensitive: false,
    },
    migrationsDb: {
      adapter : 'sails-mysql',
      host    : 'localhost',
      port    : 3306,
      user    : 'root',
      password: '',
      database: 'consumer_payment',
      rollbackTransactionOnError: true,
      queryCaseSensitive: false,
    }

  },
```

**Comment by sapnajindal** [comment]
@shamasis  Any clue on -
`AdapterError: Invalid connection name specified`

**Comment by sapnajindal** [comment]
> With sails-mysql adapter it was working very much fine, but with using sails-mysql-transactions, its taking way too much time to fetch the data.

Actually, this query is having a lot of data which sails-mysql is able to load, but sails-mysql-transactions is not. Is there any data limit for the query in your modue?

**Comment by shamasis** [comment]
There's no limit I know.

**Comment by sapnajindal** [comment]
@shamasis It has. Try a find query without filter with table having around 600 rows.

**Comment by shamasis** [comment]
We usually query over 10k rows as well. I will check though.

**Comment by sapnajindal** [comment]
querying 10k rows without filters works fine?

**Comment by shamasis** [comment]
Yes. But that doesn't mean your case should work too. There are a number of other factors.

**Comment by sapnajindal** [comment]
Okay, so how do i know about the culprit?

**Comment by shamasis** [comment]
Try running the NodeJS debugger and step through your code to see where it is failing.

**Comment by sapnajindal** [comment]
I did that,
If i run the following query 
`Model.find().populate('model1').populate('model2').limit(100)`
It works fine, but if run the above query without limit, it time outs
`Model.find().populate('model1').populate('model2')`

**Comment by sapnajindal** [comment]
@shamasis Did you check the above query? Can you please check if using populate makes the query slow on your side too?
Its creating a lot of problem

**Comment by shamasis** [comment]
Checked. Populate makes it slow by an expected amount.

**Comment by sapnajindal** [comment]
@shamasis But this was not as slow with sails-mysql, Whats the difference sails-mysql-transactions making?

**Comment by shamasis** [comment]
Can you try doing slow query logging and other debugging at MySQL level? Also, hope your columns that you're searching on is indexed.

**Comment by sapnajindal** [comment]
@shamasis I am having unit test cases using mocha in my application, for those i am creating a testDb. I have created two connections using sails-mysql-transactions adapter.
connections -
`testDb: {
    adapter: 'sails-mysql-transactions',
    host    : 'localhost',
    port    : 3306,
    user    : 'username',
    password: '',
    database: 'consumer_payment_test'
  },
mysqlDbDev: {
      adapter : 'sails-mysql-transactions',
      host    : 'localhost',
      port    : 3306,
      user    : 'sampleUser',
      password: 'samplePassword',
      database: 'sampleDatabase',
      rollbackTransactionOnError: true
    }`

I get this following warning -
```Warn: duplicate setup of connection found in Transactions.setup```

Can you put some light on this warning?

**Comment by sapnajindal** [comment]
@shamasis Any idea of the above warning?

**Comment by shamasis** [comment]
This adapter does not support multiple DB.
