### ISSUE TITLE
Transactions not working

### ISSUE THREAD

**Issue by joaolucas89** [postmanlabs/sails-mysql-transactions#36]
Sometimes the field "transactionId" is not injected in the tables and the transactions do not work. I wonder why.
Thank you.

**Comment by shamasis** [comment]
@joaolucas89 - this could happen if there is no value or criteria object to "carry forward" the transaction id. This is super rare. However, I am working on making this work without transactionId in database at all. It is already done for the `.count` function... need to put time to do it for all other methods.

**Comment by shamasis** [comment]
Marking this as duplicate of #1
